set :application, "stjohnev.com"
set :repository,  "git@github.com:insightmethods/#{application}.git"
set :user,        "sites"
set :domain,      "#{user}@insightmethods.com"
set :deploy_to,   "/home/sites/#{application}"
set :revision,    "origin/menu_changes"